name: push
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  linux_386:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: 386
      runs-on: ubuntu-24.04
  linux_amd64:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: amd64
      runs-on: ubuntu-24.04
  linux_arm:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: arm
      runs-on: ubuntu-24.04-arm
  linux_arm64:
    uses: ./.github/workflows/build.yaml
    with:
      GOOS: linux
      GOARCH: arm64
      runs-on: ubuntu-24.04-arm
  release:
    concurrency: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.linux_386.outputs.artifact }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.linux_amd64.outputs.artifact }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.linux_arm.outputs.artifact }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.linux_arm64.outputs.artifact }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ needs.linux_386.outputs.artifact }}
            ${{ needs.linux_amd64.outputs.artifact }}
            ${{ needs.linux_arm.outputs.artifact }}
            ${{ needs.linux_arm64.outputs.artifact }}
